### PR TITLE
Reuse services to allow for multiple Vizi applications in a page

### PR DESCRIPTION
**Pull request by klokoy**
Vizi complains if I create multiple applications on a page. This will fix the issue by reusing services if they already exists.

### CODE REVIEW

**Comment by tobscher** [comment]
Is this going to cause problems as some classes such as `Vizi.Application` and `Vizi.Graphics` are using a singleton pattern? Would they not all share the same elements (events, scene, renderer, camera, etc.)?

**Comment by klokoy** [comment]
I do not know.  It seems to work fine in my code.

**Comment by tparisi** [comment]
Tobias is right. We can't use this because many things in Vizi rely on a singleton pattern.

Instead I need to add some kind of environment object that is attached to a canvas; then we can hang all the services for a specific Vizi instance on that object. This will take me a few days to refactor and I'm about to go on vacation for a few weeks.

Kim, feel free to use this in your code for now (of course). When I make the change I am contemplating I'll let you know and then you can test it for your stuff.

Thanks for getting into this! It's an important issue that I have been kicking down the road until somebody needed it. I guess that time is now :-)

**Comment by klokoy** [comment]
Great, I´ll keep the hack for now and look out for your fix;)

**Pull request closed without merging**
